[build]
install = "npm i -g pnpm && pnpm install --frozen-lockfile"
command = "pnpm turbo run db:generate --filter=@repo/db && pnpm run build"

[start]
command = "pnpm start"

[env]
NODE_VERSION = "18"
NIXPACKS_PNPM = "true"
