[build]
install = "corepack enable && pnpm install --frozen-lockfile"
command = "pnpm turbo run db:generate --filter=@repo/db && pnpm run build"

[start]
command = "pnpm start"

[env]
NODE_VERSION = "18"
